version: '3.8'

services:
  user-service:
    build: ./userService
    container_name: userservice
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - DbKey=mongodb://10.10.10.19:27017/dictionary

  dictionary-service:
    build: ./dictionaryService
    container_name: dictionaryservice
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - DbKey=mongodb://10.10.10.19:27017/dictionary
      

  frontend:
    build: ./client
    container_name: vue_frontend
    ports:
      - "8080:80"
    depends_on:
      - user-service
      - dictionary-service